<?php

/**
 * SocietoActivityBundle
 * Copyright (C) 2011 Kousuke Ebihara
 *
 * This program is licensed under the EPL/GPL/LGPL triple license.
 * Please see the Resources/meta/LICENSE file that was distributed with this file.
 */

/**
 * IrregularConjugateList
 *
 * Thanks to Susan Jones' "Complete List of English Irregular Verbs"
 * http://www2.gsu.edu/~wwwesl/egw/verbs.htm
 *
 * @author Kousuke Ebihara <ebihara@php.net>
 */
return array(
    'awake' => 'awoke',
    'be' => 'was',
    'bear' => 'bore',
    'beat' => 'beat',
    'become' => 'became',
    'begin' => 'began',
    'bend' => 'bent',
    'beset' => 'beset',
    'bet' => 'bet',
    'bid' => 'bid',
    'bind' => 'bound',
    'bite' => 'bit',
    'bleed' => 'bled',
    'blow' => 'blew',
    'break' => 'broke',
    'breed' => 'bred',
    'bring' => 'brought',
    'broadcast' => 'broadcast',
    'build' => 'built',
    'burn' => 'burned',
    'burst' => 'burst',
    'buy' => 'bought',
    'cast' => 'cast',
    'catch' => 'caught',
    'choose' => 'chose',
    'cling' => 'clung',
    'come' => 'came',
    'cost' => 'cost',
    'creep' => 'crept',
    'cut' => 'cut',
    'deal' => 'dealt',
    'dig' => 'dug',
    'dive' => 'dove',
    'do' => 'did',
    'draw' => 'drew',
    'dream' => 'dreamed',
    'drive' => 'drove',
    'drink' => 'drank',
    'dye' => 'dyed',
    'eat' => 'ate',
    'fall' => 'fell',
    'feed' => 'fed',
    'feel' => 'felt',
    'fight' => 'fought',
    'find' => 'found',
    'fit' => 'fit',
    'flee' => 'fled',
    'fling' => 'flung',
    'fly' => 'flew',
    'forbid' => 'forbade',
    'forget' => 'forgot',
    'forego' => 'forewent',
    'forgo' => 'forwent',
    'forgive' => 'forgave',
    'forsake' => 'forsook',
    'freeze' => 'froze',
    'get' => 'got',
    'give' => 'gave',
    'go' => 'went',
    'grind' => 'ground',
    'grow' => 'grew',
    'hang' => 'hung',
    'have' => 'had',
    'hear' => 'heard',
    'hide' => 'hid',
    'hit' => 'hit',
    'hold' => 'held',
    'hurt' => 'hurt',
    'keep' => 'kept',
    'kneel' => 'knelt',
    'knit' => 'knit',
    'know' => 'knew',
    'lay' => 'laid',
    'lead' => 'led',
    'leap' => 'leaped',
    'learn' => 'learned',
    'leave' => 'left',
    'lend' => 'lent',
    'let' => 'let',
    'lie' => 'lay',
    'light' => 'lit',
    'lose' => 'lost',
    'make' => 'made',
    'mean' => 'meant',
    'meet' => 'met',
    'misspell' => 'misspelled',
    'mistake' => 'mistook',
    'mow' => 'mowed',
    'overcome' => 'overcame',
    'overdo' => 'overdid',
    'overtake' => 'overtook',
    'overthrow' => 'overthrew',
    'pay' => 'paid',
    'plead' => 'pled',
    'prove' => 'proved',
    'put' => 'put',
    'quit' => 'quit',
    'read' => 'read',
    'rid' => 'rid',
    'ride' => 'rode',
    'ring' => 'rang',
    'rise' => 'rose',
    'run' => 'ran',
    'saw' => 'sawed',
    'say' => 'said',
    'see' => 'saw',
    'seek' => 'sought',
    'sell' => 'sold',
    'send' => 'sent',
    'set' => 'set',
    'sew' => 'sewed',
    'shake' => 'shook',
    'shave' => 'shaved',
    'shear' => 'shore',
    'shed' => 'shed',
    'shine' => 'shone',
    'shoe' => 'shoed',
    'shoot' => 'shot',
    'show' => 'showed',
    'shrink' => 'shrank',
    'shut' => 'shut',
    'sing' => 'sang',
    'sink' => 'sank',
    'sit' => 'sat',
    'sleep' => 'slept',
    'slay' => 'slew',
    'slide' => 'slid',
    'sling' => 'slung',
    'slit' => 'slit',
    'smite' => 'smote',
    'sow' => 'sowed',
    'speak' => 'spoke',
    'speed' => 'sped',
    'spend' => 'spent',
    'spill' => 'spilled',
    'spin' => 'spun',
    'spit' => 'spit',
    'split' => 'split',
    'spread' => 'spread',
    'spring' => 'sprang',
    'stand' => 'stood',
    'steal' => 'stole',
    'stick' => 'stuck',
    'sting' => 'stung',
    'stink' => 'stank',
    'stride' => 'strod',
    'strike' => 'struck',
    'string' => 'strung',
    'strive' => 'strove',
    'swear' => 'swore',
    'sweep' => 'swept',
    'swell' => 'swelled',
    'swim' => 'swam',
    'swing' => 'swung',
    'take' => 'took',
    'teach' => 'taught',
    'tear' => 'tore',
    'tell' => 'told',
    'think' => 'thought',
    'thrive' => 'thrived',
    'throw' => 'threw',
    'thrust' => 'thrust',
    'tread' => 'trod',
    'understand' => 'understood',
    'uphold' => 'upheld',
    'upset' => 'upset',
    'wake' => 'woke',
    'wear' => 'wore',
    'weave' => 'weaved',
    'wed' => 'wed',
    'weep' => 'wept',
    'wind' => 'wound',
    'win' => 'won',
    'withhold' => 'withheld',
    'withstand' => 'withstood',
    'wring' => 'wrung',
    'write' => 'wrote',
);
